env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  quotes:
    - error
    - single
  no-console: 0
  import/extensions: 0
